###
GET http://localhost:5000/

###
POST http://localhost:5000/signup
Content-Type: application/json

{
    "fullname":"Akram Hossain",
    "username":"nakib4",
    "email":"nakib4@gmail.com",
    "password":"test1234"
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username":"nakib4",
    "password":"test1234"
}
###
GET http://localhost:5000/books

###
POST http://localhost:5000/addCategory
Content-Type: application/json

{
    "name":"Cate-5"
}

###
POST http://localhost:5000/createbook
Content-Type: application/json

{
    "name":"title jkl",
    "author":"Rahman Uddin",
    "categoryId":2
}

###
POST http://localhost:5000/user/collection
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJuYWtpYjQiLCJhdWRFbWFpbCI6Im5ha2liNEBnbWFpbC5jb20iLCJpYXQiOjE2NTY4NDc2NTMsImV4cCI6MTY1NjkzNDA1MywiaXNzIjoibmFraWIifQ.cggxK2uY4r5U5UOQRWI2X0PiSwvFb2QuTSHdr8QjAyg
Content-Type: application/json

{
    "bookId":5
}
###
GET  http://localhost:5000/user/collection
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJuYWtpYjQiLCJhdWRFbWFpbCI6Im5ha2liNEBnbWFpbC5jb20iLCJpYXQiOjE2NTY4NDc2NTMsImV4cCI6MTY1NjkzNDA1MywiaXNzIjoibmFraWIifQ.cggxK2uY4r5U5UOQRWI2X0PiSwvFb2QuTSHdr8QjAyg


###
POST http://localhost:5000/share/collection
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJuYWtpYjQiLCJhdWRFbWFpbCI6Im5ha2liNEBnbWFpbC5jb20iLCJpYXQiOjE2NTY4NDc2NTMsImV4cCI6MTY1NjkzNDA1MywiaXNzIjoibmFraWIifQ.cggxK2uY4r5U5UOQRWI2X0PiSwvFb2QuTSHdr8QjAyg
Content-Type: application/json

{
    "bookId":5,
    "holderUsername":"nakib2"
}

###
GET http://localhost:5000/share/collection
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJuYWtpYjQiLCJhdWRFbWFpbCI6Im5ha2liNEBnbWFpbC5jb20iLCJpYXQiOjE2NTY4NDc2NTMsImV4cCI6MTY1NjkzNDA1MywiaXNzIjoibmFraWIifQ.cggxK2uY4r5U5UOQRWI2X0PiSwvFb2QuTSHdr8QjAyg
###
GET http://localhost:5000/res